version: "3"

services:
  n1:
    image: raphasch/hotcertification
    volumes:
      - ./keys/n1:/home
      - ./keys:/home
    command: certificationserver --id 1 --thresholdkey n1.thresholdkey --privkey n1.key

  n2:
    image: raphasch/hotcertification
    volumes:
      - ./keys/n2:/home
      - ./keys:/home
    command: certificationserver --id 2 --thresholdkey n2.thresholdkey --privkey n2.key

  n3:
    image: raphasch/hotcertification
    volumes:
      - ./keys/n3:/home
      - ./keys:/home
    command: certificationserver --id 3 --thresholdkey n3.thresholdkey --privkey n3.key

  n4:
    image: raphasch/hotcertification
    volumes:
      - ./keys/n4:/home
      - ./keys:/home
    command: certificationserver --id 4 --thresholdkey n4.thresholdkey --privkey n4.key