version: "3"

services:
  n1:
    image: raphasch/hotcertification
    volumes:
      - ./keys:/home/keys
      - ./hotcertification.yml:/home
    command: certificationserver --id 1 --thresholdkey n1/n1.thresholdkey --privkey n1/n1.key

  n2:
    image: raphasch/hotcertification
    volumes:
      - ./keys:/home/keys
      - ./hotcertification.yml:/home
    command: certificationserver --id 2 --thresholdkey n2/n2.thresholdkey --privkey n2/n2.key

  n3:
    image: raphasch/hotcertification
    volumes:
      - ./keys:/home/key
      - ./hotcertification.yml:/home
    command: certificationserver --id 3 --thresholdkey n3/n3.thresholdkey --privkey n3/n3.key

  n4:
    image: raphasch/hotcertification
    volumes:
      - ./keys:/home/keys
      - ./hotcertification.yml:/home
    command: certificationserver --id 4 --thresholdkey n4/n4.thresholdkey --privkey n4/n4.key